apiVersion: v1
kind: Pod
metadata:
 name: jupyter-pod
 labels:
   app: jupyter-notebook
spec:
 containers:
 - image: gcr.io/deeplearning-platform-release/tf2-cpu.2-6
   name: jupyter
   volumeMounts:
   - name: workdir
     mountPath: /home/jupyter
   ports:
   - containerPort: 8080
     protocol: TCP
 volumes:
 - name: workdir
   emptyDir:
     medium: Memory

---

apiVersion: v1
kind: Service
metadata:
 name: jupyter-svc
spec:
 sessionAffinity: ClientIP
 ports:
   - name: https
     port: 8889
     targetPort: 8080
 selector:
   app: jupyter-notebook
